# Generated by Django 2.2.10 on 2020-02-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
