# Generated by Django 2.2.10 on 2020-02-12 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20200212_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='userid',
        ),
        migrations.AddField(
            model_name='post',
            name='userid_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
