# Generated by Django 2.2.10 on 2020-02-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200212_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userid_id',
            new_name='userid',
        ),
    ]
