# Generated by Django 2.2.10 on 2020-04-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200212_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('Resources', 'Resources'), ('Documents', 'Documents'), ('Leisure', 'Leisure'), ('Culture', 'Culture'), ('Laws', 'Laws'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
